
[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.14.1"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "~1.11.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "4.0.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.1"

[[constraint]]
  name = "github.com/gosuri/uitable"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.13"

[[override]]
  name = "github.com/imdario/mergo"
  version = "v0.3.5"

[[constraint]]
  name = "github.com/deislabs/oras"
  version = "v0.3.3"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "v0.3.3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"

# These overrides below necessary for using docker/distribution as a test dependency
[[override]]
  name = "github.com/yvasiyarov/newrelic_platform_go"
  revision = "b21fdbd4370f3717f3bbd2bf41c223bc273068e6"

[[override]]
  name = "github.com/miekg/dns"
  revision = "0d29b283ac0f967dd3a02739bf26a22702210d7a"

[[override]]
  name = "github.com/xenolf/lego"
  revision = "a9d8cec0e6563575e5868a005359ac97911b5985"

[[override]]
  name = "github.com/bugsnag/bugsnag-go"
  revision = "109a9d63f2b57c4623f4912b256bac4a7a63517d"